config/routes.rb
Eshop::Application.routes.draw do

  root 'products#index'

  post 'carts/add' => 'carts#add'
  post 'carts/update' => 'carts#update'
  post 'carts/deletelineitem' => 'carts#deletelineitem'

  get '/newuser' => 'user#new'
  post 'user/create' => 'user#create'
  get 'user/registration' => 'user#registration'
  post 'user/address' => 'user#address'
  post '/login' => 'user#login', :as => 'login'
  get '/logout' => 'user#logout', :as => 'logout'
  get "/auth/paypal/callback", to: "callback#show"

  resources :invitation do
    member do
      get :confirm
    end
  end

  get 'orders/express', to: 'orders#express'
  get 'orders/new', to: 'orders#new'
  post 'orders/completeorder' => 'orders#completeorder'

  resources :carts do
    resources :products
  end

  namespace :administration do |admin|
    resources :products
  end

  resources :products, :only => [:index]

end

app/controllers/administration/products_controller.rb
class Administration::ProductsController < ApplicationController

  def index
    @products = Product.all
    render 'administration/index'
  end

  def edit
    @product = Product.find_by_id(params[:id])
    render 'administration/edit'
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def update
    @product = Product.find_by_id(params[:id])
    product = {:name => params[:name], :description => params[:description], :category_id => params[:category]}
    if @product.update_attributes(product)
      flash[:success] = "Product updated successfully."
      redirect_to action: "index"
    else
      flash[:error] = "Please select a category."
      render 'administration/edit', :product => @product
    end
  end

  def categories
    Category.all
  end
end

app/views/administration/edit.html.erb
<div class="container-fluid">
  <div class=row">
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>
  </div>
   <%categories = controller.categories%>
  <%= form_for @product,:url => url_for(:controller => 'administration/products', :action => 'update') do |f| %>

   <%=label_tag 'name', 'Name'%>: <%=text_field_tag 'name', @product.name%><br/>
   <%=label_tag 'description', 'Description'%> :<%=text_field_tag 'description', @product.description%><br/>
   <%=label_tag 'category', 'Category'%> : <%=select_tag "category", options_from_collection_for_select(categories, "id", "name",if @product.category_id.nil?
                                                                                                                                    ""
                                                                                                                                  else
                                                                                                                                    @product.category_id
                                                                                                                                  end), prompt: "Select category" %> <br/>
  <%= submit_tag("Update Product", :class => 'btn btn-xs btn-success') %>
  <%end%>
</div>

app/views/administration/index.html.erb
<div class="row">
  <h2>Manage your products</h2>
  <div class=row">
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>
  </div>
  <ul>
  <%@products.each do |p|%>
   <li><%=p.name%> <%= link_to "Edit", edit_administration_product_path(p)%></li>
  <%end%>
  </ul>
</div>